apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: annotations.swongpai.xyz
spec:
  group: swongpai.xyz
  names:
    kind: annotations
    listKind: SwongpaiResourceList
    plural: annotations
    singular: annotation
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              annotations:
                type: array
                items:
                  type: object
                  properties:
                    key:
                      type: string
                    value:
                      type: string
                  required:
                    - key
                    - value
